name: Puppeteer M3U Scraper

on:
  schedule:
    - cron: "0 */2 * * *"  # every 2 hours
  workflow_dispatch:        # allows manual run

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install puppeteer
      - run: |
          echo "// Puppeteer script" > scraper.js
          # Paste your Puppeteer script here if you want inline
          node scraper.js
      - uses: actions/upload-artifact@v4
        with:
          name: m3u-links
          path: m3u_links.txt
